USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS BRONZE;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE BRONZE.STORE_SALES_RAW AS 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES LIMIT 500000000;

--PAHSE-3 : DATA VALIDATION (COMPLETNESS)
SELECT COUNT(*) AS TOTAL_RECORDS FROM BRONZE.STORE_SALES_RAW;
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES;

DESC TABLE BRONZE.STORE_SALES_RAW;

SELECT COUNT(*) AS TOTAL_ROWS, COUNT(ss_sales_price) AS NON_NULL_SALES_PRICE FROM BRONZE.STORE_SALES_RAW;

--OPTIONAL: CHECK MIN AND MAX SOLD DATE
SELECT MIN(ss_sold_date_sk) AS MIN_SOLD_DATE, MAX(ss_sold_date_sk) AS MAX_SOLD_DATE FROM BRONZE.STORE_SALES_RAW;